export const academyModules = [
  {
    id: "m1",
    title: "Comprendre l'écosystème digital",
    description: "Les fondamentaux d'une activité digitale rentable",
    objectives: ["Comprendre le modèle digital", "Différencier produit vs service", "Identifier son audience"],
    lessons: [
      { id: "m1l1", title: "Comment fonctionne une activité digitale", content: "Une activité digitale repose sur 3 piliers : audience, offre, distribution. Contrairement au business physique, le coût marginal est quasi nul. Tu peux servir 10 ou 10 000 clients avec le même produit. C'est ça la puissance. Le flux est : attention → confiance → transaction → transformation. Chaque étape doit être optimisée. Les meilleurs business digitaux ne vendent pas un produit, ils vendent une transformation." },
      { id: "m1l2", title: "Produit vs service", content: "Produit : scalable, vendu une fois, livré automatiquement. Service : temps contre argent, difficile à scaler. Hybride : produit + accompagnement = meilleur des deux mondes. Pour démarrer, choisis un produit si tu veux liberté, un service si tu veux cash rapide." },
      { id: "m1l3", title: "Comprendre une audience", content: "Une audience n'est pas un nombre, c'est une relation. 1000 vrais fans valent mieux que 100k followers fantômes. Identifie : qui ils sont, ce qu'ils veulent, ce qui les bloque. Écoute leurs conversations, pas tes suppositions." },
      { id: "m1l4", title: "Construire une proposition de valeur", content: "Ta proposition de valeur = résultat spécifique pour personne spécifique en temps spécifique. Exemple : 'J'aide les coachs à passer de 0 à 10k/mois en 90 jours sans pub'. Sois précis, pas générique." },
      { id: "m1l5", title: "Les erreurs des débutants", content: "1) Vouloir plaire à tout le monde 2) Créer avant de vendre 3) Perfectionnisme 4) Pas de preuve 5) Pas de suivi. Évite ça et tu es déjà dans le top 10%." },
    ],
  },
  {
    id: "m2",
    title: "Trouver et définir son offre",
    description: "Créer une offre irrésistible qui se vend",
    objectives: ["Identifier problème rentable", "Définir client idéal", "Construire offre"],
    lessons: [
      { id: "m2l1", title: "Identifier un problème rentable", content: "Un problème rentable = douloureux + urgent + reconnu + budget pour solution. Score chaque idée sur 10 pour ces 4 critères. Vise 32+/40." },
      { id: "m2l2", title: "Définir son client idéal", content: "Avatar : démographie, psychographie, comportements, objections. Va parler à 10 personnes réelles. Pas de persona inventé." },
      { id: "m2l3", title: "Construire une offre", content: "Offre = produit + bonus + garantie + urgence. Le produit résout le problème principal, les bonus lèvent les objections secondaires." },
      { id: "m2l4", title: "Positionnement", content: "Tu ne peux pas être le moins cher et le meilleur. Choisis : premium, accessible, ou spécialiste. Spécialiste gagne toujours au début." },
      { id: "m2l5", title: "Pricing", content: "Prix = valeur perçue, pas coût. Teste 3 prix : 297, 497, 997. Le prix trop bas attire les mauvais clients." },
      { id: "m2l6", title: "Bonus", content: "Bonus doit avoir valeur réelle, pas remplissage. Chaque bonus lève une objection précise. 3-5 bonus max, valeur totale 2x prix principal." },
      { id: "m2l7", title: "Garantie", content: "Garantie lève le risque. 30 jours satisfait ou remboursé minimum. Garantie conditionnelle plus puissante : 'si tu fais X et pas de résultat, je te rembourse + 100€'." },
      { id: "m2l8", title: "Offre irrésistible", content: "Combine tout : résultat clair + bonus pertinents + garantie forte + urgence réelle. L'offre doit être tellement bonne que ne pas acheter semble illogique." },
    ],
  },
  {
    id: "m3",
    title: "Construire son tunnel",
    description: "Le système qui transforme visiteurs en clients",
    objectives: ["Landing page", "Capture leads", "Checkout optimisé"],
    lessons: [
      { id: "m3l1", title: "Landing page", content: "Une idée par page. Headline = promesse + bénéfice + temps. Pas de menu, pas de distraction. Un seul CTA." },
      { id: "m3l2", title: "Capture de leads", content: "Lead magnet = solution à micro-problème. Valeur immédiate, consommation < 15min. Exemple : checklist, template, mini-formation." },
      { id: "m3l3", title: "Page de vente", content: "Structure : hook, problème, solution, preuve, offre, garantie, FAQ, CTA. Chaque section lève une objection." },
      { id: "m3l4", title: "Checkout", content: "Checkout court : email, paiement, c'est tout. Pas de champs inutiles. Trust badges, garantie visible. 1-click upsell après paiement." },
      { id: "m3l5", title: "Upsell", content: "Upsell = accélérateur du résultat principal. Prix 50% du principal max. Un seul upsell bien fait vaut mieux que 3 moyens." },
      { id: "m3l6", title: "Confirmation", content: "Page de confirmation = début de l'expérience, pas fin de vente. Donne accès immédiat + prochaines étapes + bonus surprise." },
      { id: "m3l7", title: "Suivi client", content: "Les 7 premiers jours déterminent tout. Onboarding email + quick win + support réactif = rétention + témoignages." },
    ],
  },
  {
    id: "m4",
    title: "Créer sa première formation",
    description: "De l'idée au produit fini",
    objectives: ["Structurer programme", "Créer contenu", "Expérience étudiante"],
    lessons: [
      { id: "m4l1", title: "Trouver un sujet", content: "Enseigne ce que tu as déjà fait, pas ce que tu as lu. Ton expérience > théorie. Valide avec 5 personnes prêtes à payer avant de créer." },
      { id: "m4l2", title: "Structurer le programme", content: "Résultat final → étapes → modules → leçons. Chaque leçon = une transformation micro. 5-15 min par leçon max." },
      { id: "m4l3", title: "Créer les modules", content: "Module = une étape vers résultat. 3-8 modules max. Ordre logique, pas chronologique de ton apprentissage." },
      { id: "m4l4", title: "Créer les vidéos", content: "Outil : Loom, iPhone, micro 50€. Pas besoin de studio. Son clair > image 4K. Coupe les blancs, ajoute chapitres." },
      { id: "m4l5", title: "Créer les supports", content: "PDF, template, checklist pour chaque leçon. Les supports augmentent la valeur perçue et le taux de complétion." },
      { id: "m4l6", title: "Créer des quiz", content: "Quiz = ancrage + validation. 3-5 questions par module. Pas piégeux, renforce l'apprentissage." },
      { id: "m4l7", title: "Créer une expérience étudiante", content: "Progression visible, célébrations, communauté, support. Un étudiant qui finit devient ambassadeur." },
    ],
  },
  {
    id: "m5",
    title: "Acquisition",
    description: "Attirer les bonnes personnes",
    objectives: ["Contenu organique", "Email", "Partenariats"],
    lessons: [
      { id: "m5l1", title: "Contenu organique", content: "Un contenu par jour, même moyen, bat un contenu parfait par mois. Documente, n'invente pas. Formats : court, carrousel, long." },
      { id: "m5l2", title: "Réseaux sociaux", content: "Choisis 1 plateforme principale, 1 secondaire. Pas partout. Depth > breadth. Réponds à tous les commentaires les 60 premières minutes." },
      { id: "m5l3", title: "Email marketing", content: "Email = actif que tu possèdes. Réseaux = loués. 1 email par jour minimum en lancement, 2-3 par semaine ensuite. 80% valeur, 20% vente." },
      { id: "m5l4", title: "SEO", content: "SEO = long terme. Articles qui répondent à questions précises de ton avatar. 1000 mots, structure claire, interne linking." },
      { id: "m5l5", title: "Partenariats", content: "Trouve qui a déjà ton audience. Propose valeur avant de demander. JV, podcast, bundle. 1 partenariat peut changer ton année." },
      { id: "m5l6", title: "Affiliés", content: "Affiliés = armée de vendeurs. Commission généreuse (30-50%), matériel prêt, suivi transparent. Traite-les comme clients VIP." },
    ],
  },
  {
    id: "m6",
    title: "Conversion",
    description: "Transformer l'intérêt en achat",
    objectives: ["Copywriting", "Preuve sociale", "Optimisation checkout"],
    lessons: [
      { id: "m6l1", title: "Copywriting", content: "Écris comme tu parles. Une personne, pas une foule. Bénéfices > fonctionnalités. 'Tu' > 'Je'. Verbes d'action." },
      { id: "m6l2", title: "Preuve sociale", content: "Témoignages spécifiques > génériques. 'J'ai gagné 5k en 30 jours' > 'Super formation'. Vidéo > texte > étoiles." },
      { id: "m6l3", title: "Objections", content: "Liste toutes les objections. Réponds-y avant qu'on les pose. Prix, temps, compétence, confiance. Chaque objection non traitée = vente perdue." },
      { id: "m6l4", title: "CTA", content: "Un CTA par section, même message. Verbe + bénéfice + urgence douce. 'Je veux + résultat' > 'Acheter'." },
      { id: "m6l5", title: "Checkout", content: "Teste : 1 vs 2 colonnes, avec vs sans order bump, prix barré vs non. Petits changements = gros impacts." },
      { id: "m6l6", title: "A/B testing", content: "Teste une chose à la fois. 100 conversions minimum par variante. Documente tout. La plupart des tests échouent, c'est normal." },
    ],
  },
  {
    id: "m7",
    title: "Automatisation",
    description: "Faire plus avec moins",
    objectives: ["Séquences email", "Segmentation", "Workflows"],
    lessons: [
      { id: "m7l1", title: "Leads", content: "Tag chaque lead : source, intérêt, température. Pas de tag = pas de personnalisation = pas de conversion." },
      { id: "m7l2", title: "Séquences email", content: "Séquence bienvenue : 5-7 emails sur 7 jours. Valeur, histoire, preuve, offre douce. Taux d'ouverture > 50% attendu." },
      { id: "m7l3", title: "Segmentation", content: "Segmente par comportement, pas démographie. A cliqué, a acheté, a regardé 50%, a abandonné panier. Comportement prédit futur." },
      { id: "m7l4", title: "Tags", content: "Convention : source:instagram, interest:copywriting, status:customer, level:advanced. Cohérent, sinon chaos." },
      { id: "m7l5", title: "Déclencheurs", content: "Déclencheur = événement qui lance automation. Inscription, achat, abandon, complétion. Chaque déclencheur = opportunité." },
      { id: "m7l6", title: "Workflows", content: "Workflow visuel : si → alors → attendre → si. Garde simple au début. 3-5 étapes max. Complexifie après résultats." },
    ],
  },
  {
    id: "m8",
    title: "Croissance",
    description: "De 0 à 100k et au-delà",
    objectives: ["KPIs", "Optimisation", "Scaling"],
    lessons: [
      { id: "m8l1", title: "KPIs", content: "4 KPIs qui comptent : CAC, LTV, marge, churn. Si tu ne mesures pas, tu ne peux pas améliorer. Dashboard simple > complexe." },
      { id: "m8l2", title: "Analytics", content: "Regarde où les gens abandonnent. Funnel : 100% landing → 40% lead → 10% checkout → 3% achat. Améliore le plus gros leak d'abord." },
      { id: "m8l3", title: "Optimisation", content: "Optimise ce qui marche déjà, pas ce qui est cassé. 10% d'amélioration sur funnel qui convertit = plus que refaire tout." },
      { id: "m8l4", title: "Upsells", content: "Upsell augmente AOV sans augmenter CAC. Offre complémentaire logique. 20-30% de take rate = bon." },
      { id: "m8l5", title: "Cross-sells", content: "Cross-sell = autre produit après 7-14 jours. Basé sur achat précédent. Email personnalisé, pas broadcast générique." },
      { id: "m8l6", title: "Affiliations", content: "Recrute affiliés parmi tes meilleurs clients. Ils connaissent produit, audience similaire. Commission + bonus performance." },
      { id: "m8l7", title: "Scaling", content: "Scale ce qui est rentable et prévisible. Pas avant. Documente processus, embauche pour tâches répétitives, garde création." },
    ],
  },
];
